[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "lazyfunc"
description = "Wrapper for callables in Python, enabling many operations between them, with lazy evaluation."
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
keywords = []
authors = [
  { name = "Josh Read", email = "joshua-read@hotmail.co.uk" },
]
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = []
dynamic = ["version"]

[project.urls]
Documentation = "https://github.com/josh-read/lazyfunc#readme"
Issues = "https://github.com/josh-read/lazyfunc/issues"
Source = "https://github.com/josh-read/lazyfunc"

[tool.hatch.version]
path = "src/lazyfunc/__about__.py"

[dirs.env]
virtual = ".venv"

[tool.hatch.envs.default]
dependencies = [
  "pytest",
  "pytest-cov",
  "numpy",
]
[tool.hatch.envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=mfunc --cov=tests {args}"
no-cov = "cov --no-cov {args}"

[[tool.hatch.envs.test.matrix]]
python = ["39", "310", "311"]

[tool.coverage.run]
branch = true
parallel = true
omit = [
  "src/lazyfunc/__about__.py",
]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
